export default {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
        "colors": {
                "surface-variant": "#e4e2e4",
                "on-primary": "#ffffff",
                "primary": "#1d2b3e",
                "surface-tint": "#515f74",
                "on-error-container": "#93000a",
                "inverse-surface": "#303032",
                "on-background": "#1b1b1d",
                "surface-container-low": "#f5f3f5",
                "tertiary-fixed-dim": "#dfc299",
                "secondary": "#505f76",
                "inverse-on-surface": "#f2f0f2",
                "on-secondary-fixed": "#0b1c30",
                "surface-bright": "#fbf9fa",
                "primary-container": "#334155",
                "on-tertiary": "#ffffff",
                "surface": "#fbf9fa",
                "surface-container-lowest": "#ffffff",
                "outline": "#75777d",
                "primary-fixed": "#d5e3fd",
                "inverse-primary": "#b9c7e0",
                "on-primary-container": "#9eadc5",
                "secondary-fixed": "#d3e4fe",
                "on-surface-variant": "#44474c",
                "on-secondary": "#ffffff",
                "secondary-fixed-dim": "#b7c8e1",
                "surface-container-high": "#eae7e9",
                "error": "#ba1a1a",
                "outline-variant": "#c5c6cd",
                "secondary-container": "#d0e1fb",
                "surface-container-highest": "#e4e2e4",
                "background": "#fbf9fa",
                "on-surface": "#1b1b1d",
                "on-primary-fixed": "#0d1c2f",
                "on-tertiary-fixed-variant": "#574424",
                "on-tertiary-container": "#c3a881",
                "on-error": "#ffffff",
                "surface-dim": "#dbd9db",
                "on-tertiary-fixed": "#281901",
                "tertiary-fixed": "#fcdeb3",
                "surface-container": "#efedef",
                "tertiary": "#38270a",
                "tertiary-container": "#503d1e",
                "error-container": "#ffdad6",
                "on-primary-fixed-variant": "#3a485c",
                "primary-fixed-dim": "#b9c7e0",
                "on-secondary-container": "#54647a",
                "on-secondary-fixed-variant": "#38485d"
        },
        "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
        },
        "spacing": {
                "unit": "4px",
                "max-width": "1440px",
                "margin-desktop": "32px",
                "margin-mobile": "16px",
                "gutter": "16px",
                "sidebar-width": "260px",
                "container-padding": "24px",
                "row-height-dense": "40px",
                "row-height-standard": "52px",
                "navbar-height": "64px"
        },
        "fontFamily": {
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "body-md": ["Inter"],
                "label-sm": ["Inter"],
                "headline-xl": ["Inter"],
                "headline-lg": ["Inter"],
                "body-sm": ["Inter"],
                "headline-md": ["Inter"],
                "body-lg": ["Inter"],
                "headline-sm": ["Inter"],
                "data-cell": ["Inter"],
                "label-caps": ["Inter"]
        },
        "fontSize": {
                "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "headline-lg-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
                "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
                "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "data-cell": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }]
        }
    },
  },
  plugins: [],
}
