export default {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
        "colors": {
                "primary": "#3B82F6",
                "on-primary": "#ffffff",
                "primary-container": "#DBEAFE",
                "on-primary-container": "#1E3A8A",
                "primary-fixed": "#BFDBFE",
                "on-primary-fixed": "#1E3A8A",
                "primary-fixed-dim": "#93C5FD",
                "on-primary-fixed-variant": "#1D4ED8",
                "secondary": "#111827",
                "on-secondary": "#ffffff",
                "secondary-container": "#374151",
                "on-secondary-container": "#F9FAFB",
                "secondary-fixed": "#4B5563",
                "on-secondary-fixed": "#ffffff",
                "secondary-fixed-dim": "#6B7280",
                "on-secondary-fixed-variant": "#F3F4F6",
                "tertiary": "#F59E0B",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#FEF3C7",
                "on-tertiary-container": "#78350F",
                "tertiary-fixed": "#FDE68A",
                "on-tertiary-fixed": "#78350F",
                "tertiary-fixed-dim": "#FCD34D",
                "on-tertiary-fixed-variant": "#B45309",
                "error": "#EF4444",
                "on-error": "#ffffff",
                "error-container": "#FEE2E2",
                "on-error-container": "#7F1D1D",
                "background": "#F9FAFB",
                "on-background": "#111827",
                "surface": "#ffffff",
                "on-surface": "#111827",
                "surface-variant": "#F3F4F6",
                "on-surface-variant": "#6B7280",
                "outline": "#9CA3AF",
                "outline-variant": "#E5E7EB",
                "surface-bright": "#ffffff",
                "surface-dim": "#D1D5DB",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#F9FAFB",
                "surface-container": "#F3F4F6",
                "surface-container-high": "#E5E7EB",
                "surface-container-highest": "#D1D5DB",
                "inverse-surface": "#111827",
                "inverse-on-surface": "#F9FAFB",
                "inverse-primary": "#93C5FD",
                "surface-tint": "#3B82F6"
        },
        "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
        },
        "spacing": {
                "unit": "4px",
                "max-width": "1440px",
                "margin-desktop": "32px",
                "margin-mobile": "16px",
                "gutter": "16px",
                "sidebar-width": "260px",
                "container-padding": "24px",
                "row-height-dense": "40px",
                "row-height-standard": "52px",
                "navbar-height": "64px"
        },
        "fontFamily": {
                "label-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "body-md": ["Inter"],
                "label-sm": ["Inter"],
                "headline-xl": ["Inter"],
                "headline-lg": ["Inter"],
                "body-sm": ["Inter"],
                "headline-md": ["Inter"],
                "body-lg": ["Inter"],
                "headline-sm": ["Inter"],
                "data-cell": ["Inter"],
                "label-caps": ["Inter"]
        },
        "fontSize": {
                "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "headline-lg-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
                "headline-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
                "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "data-cell": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }]
        }
    },
  },
  plugins: [],
}
